name: nepvent_waiter
description: A new Flutter project.
publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 3.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  dio: ^5.8.0+1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  qr_flutter: ^4.1.0
  simple_barcode_scanner: ^0.3.0
  web_socket_channel: ^3.0.3
  flutter_local_notifications: ^19.4.0
  socket_io_client: ^3.1.2
  provider: ^6.1.5
  intl: ^0.20.2
  nepali_date_picker: ^7.0.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.4
  sunmi_printer_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie_animations/
    - assets/sound/
    - assets/icon/
    - assets/PaymentMethodIcon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/notification_Icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  # Add custom fonts here if used
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
