final Map<String, String> urls = {
  'login': 'auth/login',
  'tableLocation': 'table-location',
  'tables': "table?locationOnly=false&orderSource=TABLE",
  'menuPrimaryCategory': "menu-primary-category/menu",
  'getEstimate': "invoice/estimate",
  'mergeTable': "table/merge",
  'changeTable': "table/change",
  'joinTable': "join_table",
  'qr': "tenant_setting",
  'profile': "profile/restaurant",
  'paymentMethod': "payment-option",
  'coupon': "invoice/coupon",
  'ticketType': "other-charge/?couponOnly=true",
  'ticketHistory': "reports/couponReceipts/?type=D",
  'ReprintCoupon': "/payment/payment-receipt",
  'RangeFilter': "/reports/couponReceipts",
  'getInvoice': "/invoice/",
  'generateDQR': "/payment/qr/generate",
  'checkDQRStatus': "/payment/qr/",
  'payment': "/payment/",
  'paymentOptions': "/payment-option/",
};
